### ISSUE TITLE
多节点延迟测试闪退

### ISSUE THREAD

**Issue by IcemBerry** [TheCGDF/SSD-Android#23]
机型: SM-G9600
Android 版本: 9.0
点击右上角测速图标后开始测速，测速一半时闪退，打开后再次执行测速，未完成测速且闪退，反复五次后，第五次完成了测速且未闪退，如需要我提供调试日志请告知位置。

**Comment by CGDF-Github** [comment]
如果有安装adb的电脑，可以手机开启开发者模式连接电脑后使用adb logcat输出日志。
如果没有以上条件，请尝试再进行几次测速操作，如果还能复现闪退，请尝试定位一下测到哪个节点时闪退会发生。
或者，请尝试卸载并重新安装SSD，或者更换设备（如果有的话），以确认是否依然可以复现

**Comment by IcemBerry** [comment]
我又尝试了几次，包括删除重装、设备重启、节点重新添加等操作，此Bug是偶然发生的，但一旦发生就会反复出现，发生条件未知(几次操作情况基本一致)，比较幸运的抓到了日志，请看这里: [catlog@gist](https://gist.githubusercontent.com/IcemBerry/9ce337ced86193cdc26bce453826f957/raw/ade7b384e2139b773c35cff42b54163961d3a47d/logcat.log)

**Comment by CGDF-Github** [comment]
[mobile-universal-debug.zip](https://github.com/CGDF-Github/SSD-Android/files/2935699/mobile-universal-debug.zip)

请尝试一下这个版本，如果依然会崩溃，还请再保存一下logcat

**Comment by IcemBerry** [comment]
我已经尝试此版本12个小时了，期间使用了WiFi、移动数据在不同位置进行了测试，目前暂未出现崩溃的情况，但出现过检测某个节点卡住(检测功能不工作，其他正常)的情况，此时再次发起测试即可继续检测。我会保持观察，如果出现崩溃，尽量抓取日志。
