### ISSUE TITLE
自定义规则的在线规则文件URL用不了

### ISSUE THREAD

**Issue by dozen007** [TheCGDF/SSD-Android#27]
issue的用途：

√ 提交BUG
自定义规则的在线规则文件URL用不了

URL地址：https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/assets/acl/gfwlist.acl

**Comment by CGDF-Github** [comment]
1。这是SS/SSD内置的ACL，不是很懂你又去特意翻个在线链接然后加进去是几个意思？

2。就当是你很有想法好了，但是我测试过了，并没有发现什么BUG，Please提供点详细信息行吗？

**Comment by dozen007** [comment]
自定义界面出现的是链接，而不是链接里面的内容

**Comment by CGDF-Github** [comment]
所以显示链接就不能用了？？？

**Comment by dozen007** [comment]
是的，自定义规则只有这个链接，然后路由设置选择自定义规则，SSD就连不上节点

**Comment by CGDF-Github** [comment]
显示“后台服务启动失败”？
还是连接后没流量？

艹能不能一次性说清楚点。。。

**Comment by CGDF-Github** [comment]
这个是上游BUG，下个版本修，如果你要用那个URL的规则，直接选“GFW List”就行了

**Comment by dozen007** [comment]
好的，我个人有更新强迫症，看到ss的那个ACL是1个月前更新的，而SSD是7个月前，所以想用ss那个ACL

**Comment by CGDF-Github** [comment]
![image](https://user-images.githubusercontent.com/17256673/54932633-18996a80-4f56-11e9-80f9-c17080eb32ec.png)
嗯？你确定？ 7个月前？？？ 7个月前有SSD了吗？？？

**Comment by CGDF-Github** [comment]
这个仓库是6个月前开的，谢谢

**Comment by CGDF-Github** [comment]
哦我明白你的意思了，SSD的ACL的确不是最新的

**Comment by cesaryuan** [comment]
等待作者下个版本修复
