### ISSUE TITLE
nexus 6p用不了。

### ISSUE THREAD

**Issue by DreamChanSS** [TheCGDF/SSD-Android#28]
issue的用途：

√ 提交BUG

x 申请新功能

× 用法咨询

× 其他

---

请先搜索一遍自己想提的内容是否已有人提过

请谨慎斟酌自己的issue是否值得一提

如果是提交BUG，请详细描述导致BUG的步骤

如果是申请新功能，请先想清楚是否应该先发到Shadowsocks上游

---

作者耐心很差，请勿提傻逼issue浪费作者时间

傻逼issue会被lock，傻逼会被block

不给华为用可不可以不要这么严格，华为代工而已。nexus6p很尴尬。

**Comment by TheCGDF** [comment]
这个问题下个版本应该会修复，不过手头正在做的版本，尝试性改动比较多，所以最近没commit上来，等等哪天可能就会突然发布个新版本

**Comment by DreamChanSS** [comment]
好的，辛苦了～只能暂时用别的了。

**Comment by TheCGDF** [comment]
我没有Nexus设备，所以有没有受此问题影响的Nexus用户有兴趣试一下这个debug版本？（debug版本安装之前请先卸载旧版
[mobile-universal-debug.zip](https://github.com/TheCGDF/SSD-Android/files/3125582/mobile-universal-debug.zip)
）

**Comment by Un1Gfn** [comment]
## Nexus 6P 全自动手工测试报告

版本: [975afd2](https://github.com/TheCGDF/SSD-Android/tree/975afd2970b68700bed31295b049fd4578de899a)

从 [CircleCI](https://circleci.com/gh/Un1Gfn/SSD-ci/16#artifacts) 下载 由 [脚本](https://github.com/Un1Gfn/SSD-ci/blob/master/.circleci/config.yml) 全自动非手工生成的 **mobile-arm64-v8a-release-signed-aligned.apk** 不需要登录 不需要登录 不需要登录 重要的事情说三遍

<details><summary>Nexus_6P x LineageOS_15.1 环境</summary>

```bash
$ adb shell getprop | fgrep -i -e [ro.build -e [ro.product -e [ro.vendor
[ro.build.characteristics]: [nosdcard]
[ro.build.date]: [Fri Apr 26 14:18:22 UTC 2019]
[ro.build.date.utc]: [1556288302]
[ro.build.description]: [angler-user 8.1.0 OPM7.181205.001 5080180 release-keys]
[ro.build.display.id]: [lineage_angler-userdebug 8.1.0 OPM7.181205.001 98d5e77ab5]
[ro.build.fingerprint]: [google/angler/angler:8.1.0/OPM7.181205.001/5080180:user/release-keys]
[ro.build.flavor]: [lineage_angler-userdebug]
[ro.build.host]: [lineage-runner]
[ro.build.id]: [OPM7.181205.001]
[ro.build.product]: [angler]
[ro.build.selinux]: [0]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [gitlab-runner]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [5080180]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [8.1.0]
[ro.build.version.sdk]: [27]
[ro.build.version.security_patch]: [2018-12-05]
[ro.product.board]: [angler]
[ro.product.brand]: [google]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [angler]
[ro.product.first_api_level]: [23]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Huawei]
[ro.product.model]: [Nexus 6P]
[ro.product.name]: [angler]
[ro.vendor.build.date]: [Fri Oct 19 16:45:06 UTC 2018]
[ro.vendor.build.date.utc]: [1539967506]
[ro.vendor.build.fingerprint]: [google/angler/angler:8.1.0/OPM7.181205.001/5080180:user/release-keys]
[ro.vendor.extension_library]: [libqti-perfd-client.so]
[ro.vendor.product.brand]: [google]
[ro.vendor.product.device]: [angler]
[ro.vendor.product.manufacturer]: [Huawei]
[ro.vendor.product.model]: [Nexus 6P]
[ro.vendor.product.name]: [lineage_angler]
```

</details>

<details><summary>冇毛病 正常运行 不要点开看</summary>
  
&#9875;

* 严重: Play商店后台記憶體侧漏导致下载apk时chrome连续黑屏闪退五次
  * 将chrome和商店[双杀](https://gaming.stackexchange.com/questions/97730/how-do-i-perform-a-double-assassination-in-assassins-creed-iii)解决

* 严重: LineageOS的[Trebuchet](https://github.com/LineageOS/android_packages_apps_Trebuchet/tree/lineage-15.1)抽风导致SSD安装似乎永远不能完成
  * 实际已安装完 杀[Trebuchet](https://github.com/LineageOS/android_packages_apps_Trebuchet/tree/lineage-15.1)即可正常显示

* 严重: 使用30s自动关机
  * 使用前1%电 建议摘除小白鼠大脑以减少类似问题发生

↑ 以上毛病由Play商店/[Trebuchet](https://github.com/LineageOS/android_packages_apps_Trebuchet/tree/lineage-15.1)/脑瘫小白鼠负全责, 与SSD軟體冇任何[特殊性關係](https://zh.wikipedia.org/zh-tw/特殊性關係)

收起来吧 &#9875;

</details>

以下操作正常
1. 安装
1. 显示界面
1. [去广告](https://github.com/shadowsocks/shadowsocks-android/issues/669#issuecomment-216253449)
1. 订阅
1. 更订阅
1. 连接节点(截图)
1. chrome浏览GitHub的姊妹网站(截图)
1. 使用Telegram水群

以下未做测试
* 多个订阅
* 订阅/散装节点混合
* 右上角那个图标是不是让手机放高压电的意思 不敢试 (迫真)
* 导入导出
* 分应用代理
* [TCP Fast Open](https://en.wikipedia.org/wiki/TCP_Fast_Open)
* [抗下毒](https://www.grc.com/dns/dns.htm)

其余母鸡

<details><summary>懒, 冇logcat，有截图</summary>

![photo_2019-04-30_17-22-39](https://user-images.githubusercontent.com/28521292/56955134-1ccb3000-6b73-11e9-889d-44045788d11c.jpg)
![photo_2019-04-30_17-22-52](https://user-images.githubusercontent.com/28521292/56955153-2a80b580-6b73-11e9-87b0-04065a2aadcd.jpg)
![photo_2019-04-30_17-23-01](https://user-images.githubusercontent.com/28521292/56955165-310f2d00-6b73-11e9-9f24-b5980576cfd8.jpg)
![photo_2019-04-30_17-22-45](https://user-images.githubusercontent.com/28521292/56955172-379da480-6b73-11e9-9185-8b1f33e0fd0f.jpg)

</details>

Thank you !

**Comment by Un1Gfn** [comment]
@DreamChanSS 五楼apk使用弱爆了的明文密码000000临柜生成的keystore签名 生成后即刻丢弃 故覆盖安装有[高达八成](http://cn.uncyclopedia.wikia.com/wiki/%E9%AB%98%E8%BE%BE%E5%85%AB%E6%88%90)的几率要失败 且[没有人](http://cn.uncyclopedia.wikia.com/wiki/%E6%B2%A1%E6%9C%89%E4%BA%BA)能掘出原keystore用以签出可覆盖型apk 请注意备份节点信息 谢谢
