### ISSUE TITLE
instagram用不了

### ISSUE THREAD

**Issue by Twizere** [TheCGDF/SSD-Android#32]
issue的用途：

√ 提交BUG ： Instagram 用不了

√ 申请新功能

× 用法咨询

× 其他

---

请先搜索一遍自己想提的内容是否已有人提过

请谨慎斟酌自己的issue是否值得一提

如果是提交BUG，请详细描述导致BUG的步骤：
 其他的app可以用包括（youtube, google, ..） 但是 Instagram 不能用，连接失败， 我在原版ss 4.1.4上用一样节点Instagram 可以用。

**Comment by Twizere** [comment]
能不能解决这个问题？

**Comment by TheCGDF** [comment]
ipv6转发是开着的？

**Comment by Twizere** [comment]
是的， ipv6转发开着的

**Comment by TheCGDF** [comment]
@Twizere 关掉试试

**Comment by Twizere** [comment]
关掉了还是不行

**Comment by TheCGDF** [comment]
如果有空，是否可以试一试原版4.7.1是否可以访问？
