### ISSUE TITLE
关于SSD的一些建议

### ISSUE THREAD

**Issue by g5239277** [TheCGDF/SSD-Android#34]
√ 建议

首先感谢作者的辛苦努力，让广大非IT专业科学上网用户，可以更为方便地使用SS服务。关于SSD有一些建议：
1、在SSD连接期间可以测延时。我理解的是由于Android限制，代理被SSD接管后，所有Ping都要经过代理，所以不能连接是测Ping值。这个可以解决么，这样使用起来更加方便（跟PC端一样了）。
2、增加订阅内单个节点手动测延时功能。这样在某些节点中断期间，需要紧急使用时不必等待所有节点测试（挨个连接后测试也比较慢），可以快速恢复外网访问。
3、订阅排序规则。主要是不太了解，因为就2家机场在用。如果可以，增加一个手动排序，感觉会方便些。
4、去除机型限制。这个本不想提，因为作者有自己独立的看法，但是通过这一段时间查看作者对Issues解决的认真和回复的诚恳，感觉只是可能对有些信息不太了解，造成了一些误解，我在这解释说明一下。在作者的认识里，可能国产UI有后台，可以偷窥、转输你的隐私、数据等一些列东西，比较反感。
在这里我提两点，一是只要你还在用任何一款软件、使用国内手机号、国内网络服务（以及“友好国家”的各类服务）等，相关部门就可以通过IMEI、手机号等抽取你手机中的任何信息。在国家机器面前，你没有任何隐私，一个UI并不能规避这种风险。二是SSD的初衷，作者提到过：
> [Desgin for Airport/为机场设计]是SSD的重要[立项原因、开发理念]之一

而既然目标是机场，那么用户有基础的也不会多，基本就是“芸芸众生”。这些人用非国产UI的可能性有多少呢？恐怕超过2成的难度很大，基本也就是和一般国内手机用户选择差不多，华米OV，偶尔来个一加、锤子。如果把这几家都封禁，那基本也就没用户了，这和作者的初衷恐怕是南辕北辙，这也是目前支持SSD订阅机场较少的一个原因（支持的机场，放在网页上的版本基本都是0.03，因为要考虑所有用户）。
        对于PC，360之类的很多早就不用了，因为臃肿、难用，而且可替代性很高，相对影响并不大；对于手机，国内UI的方便程度远不是国外UI可比拟的暂且不说，但UI并不是软件，不是普通用户说换就能换的，这个基本就是无解的了。

暂时就想到这几点，想到哪说到哪，希望作者不要介意。再次感谢作者提供了这么好的软件，谢谢。

**Comment by Un1Gfn** [comment]
活著真的不好嗎

**Comment by efsg** [comment]
我们这些改机型骗流氓的该怎么办？

**Comment by TheCGDF** [comment]
1、你的理解是正确的，目前（我）无法解决，如果有解决方案欢迎提出
2/3、因为（我个人）感觉这样的功能意义不大，目前也没有看到其他人提出同类需求（同时我自己也没有），如果后续有人提出此需求我会再考虑。我比较倾向于不对原版SS做太多改动，否则升级的时候会很蛋疼
4、我之前有个SSRR的仓库，现在转让给别人了。转让之前，那个仓库的readme中，有这样一段话
```
“反全家桶机制”的目的并非“防止各类全家桶收集信息”，因为只要稍微用大脑思考即可发现这完全不切实际
……
这一系列的机制和思想亦存在于SSD项目中
```
关于的SSD的初衷，我不是很懂为何你强行无视wiki中紧接着你引用那句的两行话
```
但请不要误会，SSD没有任何类似于“造福众生”的意思，对“扩大受众范围”此类行为 毫·无·兴·趣
[为机场设计]不是“为所有机场设计”，而是“这种设计，比起个人用户，更适合机场订阅用户”
```

我对国产全家桶收集隐私、屈服于国家机器什么的完全不感兴趣
我又不是super hero
我只是不喜欢小白，我自己设计了这么个法子提高一下门槛、过滤一下小白
我没有原版SS团队那么强的耐心
他们能逐条回复issue里大片大片的傻屌问题，我不行，我鶸
小白可以等到自己不是小白的时候再来用

**Comment by g5239277** [comment]
首先感谢作者认真的回复。我这次写此Issues，其实作者应该看的出来，比较认真的准备了一下，因为确实一直希望有这么一款支持原版协议的SS订阅软件出现，所以对作者的项目很是关注。平时工作时间忙，这个Issues小两个月前就想提了，一直拖到现在。考虑到作者的想法，写了差不多2个多小时，做了多次修改。由于今天时间比较紧，我就直接表达了，望见谅。

关于2/3点是提议，第2点分节点延时测试，需求者还是很多的，实用性挺强。
第3点确实不太多，一个人保有2家机场其实就很多了，确实如你所说需求不是那么强烈。

关于第4点，先说一点，这也是我自己不好意思了。之前听人提到过，作者这样做是为了防小白，其实我一直不信，所以才做了如上揣测和回复，实在是对不住了。我不信的主要原因是，防小白用这种方法，我认为效果寥寥，机型≠小白/非小白，下面做解释吧。

> 关于的SSD的初衷，我不是很懂为何你强行无视wiki中紧接着你引用那句的两行话

其实我很认真的看了几遍的，不是忽略，而是前后三句话，第1、3句表达的意思和第2句完全相反，而且并不能表达出“对‘扩大受众范围’此类行为 毫·无·兴·趣”的意思。这点不做扩展了，“支持订阅=扩大受众”，关键词。

> 我只是不喜欢小白，我自己设计了这么个法子提高一下门槛、过滤一下小白
我没有原版SS团队那么强的耐心
他们能逐条回复issue里大片大片的傻屌问题，我不行，我鶸
小白可以等到自己不是小白的时候再来用

作者还是这么直白，我就直说下理解，可能有所冒犯，望见谅。
1、使用SSD的用户大部分都是机场引流的“订阅用户”，都学习使用过SSR/SS等软件，有相当基础。
2、通过结果来看，Issues一共25个问题，仅类似“我是华为/xx手机，但不是原版系统，怎么不能用”就看到了2个，小白还是“反馈Bug”，难以分辨；2楼这种“认同党”其实很多。
3、正在使用SSD的机场，Android版本基本都维持在0.03，不做更新。这里面其实两个事，一是SSD其实非常好用，但目前知道的人也的确不多；二是，相关的一些限制，机场主觉得麻烦，所以直接放0.03，或者，直接不支持。
4、机型≠小白/非小白。据目前的了解，相关码农/程序员/大佬等用的手机是五花八门，除了华对外网服务做了实际限制的华为少些，其他牌子用什么的都有，中等基础用户也是，小白也是，没什么本质区别。在国内，本土化UI的闪付、公交等便捷功能，还是想用的多。而且几行检测代码，带来的非议恐怕远比褒奖大得多，原版SS作者和后续作者对开放精神是坚持不懈的，这之间貌似存在一些分歧。

说这么多，可能，作者并不赞同。但作者也明白，这肯定也不是我一个人的想法。我不是为了争辩什么，只是希望作者能换个角度想这个问题，或者用其他方法做限制，比如Surfboard的方法。这样既能达到目的，也可以让SSD项目有个更好的环境。
最后，还是感谢作者的努力和执着，让我们使用到了这么好的作品，非常感谢，同时希望作者各方面更加成熟和老练。

**Comment by TheCGDF** [comment]
你说的太多了，在本项目的issue区请精炼自己的语言，请不要动不动就开始写高考作文
2/3 需求者多不多依赖于issue区和群中的反馈，而不是某个人的一家之言
`支持订阅=扩大受众`？仅仅因为加了个功能就必须服务更多人，那我删库算了，还支持个球订阅。你还不如去说服原版SS团队扩大受众，增加个订阅功能
以及，请不要把你对“小白”的理解强行套用于我，小白指的*我*不想看到的用户，而不是*你以为我*不想看到的用户。而我，对现在的过滤效果表示满意
做人最要紧是开心，什么非议、褒奖、开放精神，老子不在乎，有这方面崇高理想请找别人谈人生，请不要擅自给我增添责任与义务。老子也不打算靠SSD盈利，扩大受众除了让我离喝茶更近一步没有任何效果，毕竟老子不用爱发电
![930038586](https://user-images.githubusercontent.com/17256673/61994947-990eda00-b0b4-11e9-892e-88de513e7b8a.jpg)

**Comment by g5239277** [comment]
好的。最后表示感谢，也感谢热心的码农/大佬，让我用上SSD。

建议：加强计算机语言以外的其他学习。

**Comment by zhihuiyuze** [comment]
希望能支持华为手机
