### ISSUE TITLE
概率性无法启动

### ISSUE THREAD

**Issue by dustofsoul** [TheCGDF/SSD-Android#36]
issue的用途：

√ 提交BUG
节点使用四级域名的情况下有概率提示无效的主机地址，强行停止并重启应用可解
原生Android 9 10均有此问题
一般在连续运行一周左右，并且通过快捷菜单关闭之后会出现
暂时没有其他好的复现方法
---

请先搜索一遍自己想提的内容是否已有人提过

请谨慎斟酌自己的issue是否值得一提

如果是提交BUG，请详细描述导致BUG的步骤

如果是申请新功能，请先想清楚是否应该先发到Shadowsocks上游

---

作者耐心很差，请勿提傻逼issue浪费作者时间

傻逼issue会被lock，傻逼会被block

**Comment by TheCGDF** [comment]
我觉得这应该是上游或者设备的锅。。。
