### ISSUE TITLE
诺基亚x71添加节点闪退，之前诺基亚x7可以正常使用，x71在恢复出厂设置之前也可以正常使用，都是安卓9系统，请问是被拉黑了吗

### ISSUE THREAD

**Issue by story2005** [TheCGDF/SSD-Android#37]
issue的用途：

√ 提交BUG

√ 申请新功能

× 用法咨询
---

请先搜索一遍自己想提的内容是否已有人提过

请谨慎斟酌自己的issue是否值得一提

如果是提交BUG，请详细描述导致BUG的步骤

如果是申请新功能，请先想清楚是否应该先发到Shadowsocks上游

---

作者耐心很差，请勿提傻逼issue浪费作者时间

傻逼issue会被lock，傻逼会被block

**Comment by TheCGDF** [comment]
@story2005 被拉黑的系统，会弹出拉黑提示消息。
如果没有提示消息，请检查该设备及网络环境是否可以正常访问Github
