### ISSUE TITLE
节点名称带有>字符订阅失败

### ISSUE THREAD

**Issue by kyle18th** [TheCGDF/SSD-Android#38]
issue的用途：

√ 提交BUG

---

最近使用机场订阅链接时一直订阅失败，TG群里问了一下，有人回答是新的节点的名字里含有>字符导致与APP冲突，不知道订阅失败是不是这个特殊字符的原因。

**Comment by TheCGDF** [comment]
![GeePlayer_rAsmuIasrj](https://user-images.githubusercontent.com/17256673/65256178-b51d7d80-db31-11e9-9791-e949dfc995a2.jpg)
未能复现此BUG

**Comment by TheCGDF** [comment]
我猜八成是你家机场地址被污染了什么的。。。

**Comment by kyle18th** [comment]
@TheCGDF 
不好意思，好像是>字符，我粘贴了其中一个名称，其他名称与这个大致类似，名称为：**N3RO>19310 沪港 (0.5 倍率) #NF #Express #Premium #Daily**，能麻烦帮忙测试一下这个吗？再不行就只能不用订阅了。

**Comment by nameless3721** [comment]
污染是没 ssd win可以订阅 ssd 安卓就不行 把N3RO>19310 内容解密批量换成N3RO19310再base64放到别的地方来才能用很玄

**Comment by TheCGDF** [comment]
![Screenshot_20190920-200253_SSD](https://user-images.githubusercontent.com/17256673/65325524-abebe980-dbe1-11e9-9d47-e89afdc63f3c.jpg)
仍然未能复现

**Comment by TheCGDF** [comment]
既然放到别的地方就能订阅，我再盲猜一下，可能是你们机场主弄了什么cloudflare规则或者nginx规则，导致SSD Android端的订阅行为被识别为爬虫了之类的

**Comment by nameless3721** [comment]
> 既然放到别的地方就能订阅，我再盲猜一下，可能是你们机场主弄了什么cloudflare规则或者nginx规则，导致SSD Android端的订阅行为被识别为爬虫了之类的

看到你这个我也觉得有可能不过你测试一下这两个 https://raw.githubusercontent.com/nameless3721/ACL4SSR/master/N3ROtest  这个是N3RO> 不行
https://raw.githubusercontent.com/nameless3721/ACL4SSR/master/N3RO   这个批量把N3RO>改成N3RO就可以了  有点玄..?

**Comment by TheCGDF** [comment]
已修复：https://github.com/TheCGDF/SSD-Android/commit/b4b64fe67a386221767fde8d06346f27abd49a79

BUG原因：该机场使用了非url安全的base64，SSD Android使用了url安全的解码方式，导致部分情况下解码会失败

修复后的安装包：（因为是debug版，如果安装不成功请尝试卸载已安装的SSD）
[mobile-universal-debug.zip](https://github.com/TheCGDF/SSD-Android/files/3636702/mobile-universal-debug.zip)

**Comment by TheCGDF** [comment]
以及，该订阅有一处不符合订阅协定：
该订阅的服务器id是从0开始的
但是根据协定，应当从1开始：
https://github.com/TheCGDF/SSD-Windows/wiki/HTTP订阅协定
![vivaldi_RTTFPi0uPV](https://user-images.githubusercontent.com/17256673/65340686-57586680-dc01-11e9-8052-b5f09cb35e95.jpg)

**Comment by nameless3721** [comment]
> 已修复：[b4b64fe](https://github.com/TheCGDF/SSD-Android/commit/b4b64fe67a386221767fde8d06346f27abd49a79)
> 
> BUG原因：该机场使用了非url安全的base64，SSD Android使用了url安全的解码方式，导致部分情况下解码会失败
> 
> 修复后的安装包：（因为是debug版，如果安装不成功请尝试卸载已安装的SSD）
> [mobile-universal-debug.zip](https://github.com/TheCGDF/SSD-Android/files/3636702/mobile-universal-debug.zip)

谢谢 测试了 可成功订阅了  (虽然看不太懂后面说的
