### ISSUE TITLE
启动的时候会显示  后台服务启动失败：无法连接原创服务器：未知插件obfs-local

### ISSUE THREAD

**Issue by mrliu666666** [TheCGDF/SSD-Android#39]
issue的用途：
√ 用法咨询
---

请先搜索一遍自己想提的内容是否已有人提过

请谨慎斟酌自己的issue是否值得一提

如果是提交BUG，请详细描述导致BUG的步骤

如果是申请新功能，请先想清楚是否应该先发到Shadowsocks上游

---

作者耐心很差，请勿提傻逼issue浪费作者时间

傻逼issue会被lock，傻逼会被block

**Comment by TheCGDF** [comment]
艹，“用法咨询”前面打叉的意思是，issue区不可用于“用法咨询”，而不是让你改成钩再发
能Google的问题请不要发在这里

**Comment by mrliu666666** [comment]
@TheCGDF 对不起 请见谅
